// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB20HCwSyTortda4dIovxuU-jcZK5qRSbM',
    appId: '1:255124081047:web:99a39fd71088cb97d35cd2',
    messagingSenderId: '255124081047',
    projectId: 'kanngrow-ai-qwok',
    authDomain: 'kanngrow-ai-qwok.firebaseapp.com',
    storageBucket: 'kanngrow-ai-qwok.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKbTJZsA4bh__9MLxXsRIJPPAUjgQ5XK4',
    appId: '1:255124081047:android:d77714ddbbf1ee4ed35cd2',
    messagingSenderId: '255124081047',
    projectId: 'kanngrow-ai-qwok',
    storageBucket: 'kanngrow-ai-qwok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq2oJj1n7S5LDUcdOSBeiuxxJyoXm2YCY',
    appId: '1:255124081047:ios:1900ffaed8408021d35cd2',
    messagingSenderId: '255124081047',
    projectId: 'kanngrow-ai-qwok',
    storageBucket: 'kanngrow-ai-qwok.firebasestorage.app',
    iosClientId: '255124081047-fqghoioreg50kne5l3j098qt2vup5ku0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kangrowAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq2oJj1n7S5LDUcdOSBeiuxxJyoXm2YCY',
    appId: '1:255124081047:ios:1900ffaed8408021d35cd2',
    messagingSenderId: '255124081047',
    projectId: 'kanngrow-ai-qwok',
    storageBucket: 'kanngrow-ai-qwok.firebasestorage.app',
    iosClientId: '255124081047-fqghoioreg50kne5l3j098qt2vup5ku0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kangrowAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB20HCwSyTortda4dIovxuU-jcZK5qRSbM',
    appId: '1:255124081047:web:d0d5f4286fef3566d35cd2',
    messagingSenderId: '255124081047',
    projectId: 'kanngrow-ai-qwok',
    authDomain: 'kanngrow-ai-qwok.firebaseapp.com',
    storageBucket: 'kanngrow-ai-qwok.firebasestorage.app',
  );
}
