// India cities — comprehensive list covering small, mid, large, and metro cities.
const kIndiaCities = [
  'Abohar', 'Agartala', 'Agra', 'Ahmedabad', 'Ahmednagar', 'Aizawl', 'Ajmer',
  'Akola', 'Aligarh', 'Allahabad', 'Alwar', 'Ambala', 'Amravati', 'Amreli',
  'Amritsar', 'Anand', 'Anantapur', 'Anantnag', 'Arrah', 'Asansol', 'Aurangabad',
  'Ayodhya', 'Azamgarh', 'Badlapur', 'Bagaha', 'Bagalkot', 'Bahadurgarh',
  'Baharampur', 'Bally', 'Balurghat', 'Banda', 'Bangalore', 'Banswara',
  'Baramula', 'Barasat', 'Bardhaman', 'Bareilly', 'Baripada', 'Barnala',
  'Barshi', 'Basirhat', 'Basti', 'Batala', 'Bathinda', 'Beed', 'Begusarai',
  'Belgaum', 'Bellary', 'Bettiah', 'Bhadravati', 'Bhadreswar', 'Bhagalpur',
  'Bhalswa Jahangir Pur', 'Bharatpur', 'Bharuch', 'Bhatpara', 'Bhavnagar',
  'Bhilai', 'Bhilwara', 'Bhind', 'Bhiwandi', 'Bhiwani', 'Bhopal', 'Bhubaneswar',
  'Bhuj', 'Bhusawal', 'Bidar', 'Bidhan Nagar', 'Bihar Sharif', 'Bijapur',
  'Bikaner', 'Bilaspur', 'Bokaro', 'Bongaigaon', 'Bongaon', 'Budaun',
  'Bulandshahr', 'Bundi', 'Burhanpur', 'Buxar', 'Chalisgaon', 'Chandausi',
  'Chandigarh', 'Chandrapur', 'Chapra', 'Chas', 'Chennai', 'Chhapra',
  'Chhatarpur', 'Chhindwara', 'Chikmagalur', 'Chitradurga', 'Chittoor', 'Churu',
  'Coimbatore', 'Cuttack', 'Dabgram', 'Dallo Pura', 'Damoh', 'Darbhanga',
  'Darjeeling', 'Datia', 'Davanagere', 'Deesa', 'Dehradun', 'Dehri', 'Delhi',
  'Deoghar', 'Dewas', 'Dhanbad', 'Dharmavaram', 'Dharwad', 'Dhubri', 'Dhule',
  'Dibrugarh', 'Dindigul', 'Dispur', 'Durg', 'Durgapur', 'Eluru', 'Erode',
  'Etawah', 'Faizabad', 'Faridabad', 'Farrukhabad', 'Fatehpur', 'Firozabad',
  'Firozpur', 'Gadag', 'Gandhidham', 'Gandhinagar', 'Ganganagar', 'Gangapur',
  'Gangavati', 'Gangtok', 'Gaya', 'Ghaziabad', 'Ghazipur', 'Giridih', 'Godhra',
  'Gonda', 'Gondal', 'Gondia', 'Gorakhpur', 'Greater Noida', 'Gudivada',
  'Gulbarga', 'Guna', 'Guntakal', 'Guntur', 'Gurgaon', 'Guwahati', 'Gwalior',
  'Hajipur', 'Haldia', 'Haldwani', 'Halisahar', 'Hanumangarh', 'Hapur',
  'Harda', 'Hardoi', 'Haridwar', 'Hassan', 'Hathras', 'Hazaribagh', 'Hindupur',
  'Hinganghat', 'Hissar', 'Hooghly-Chinsurah', 'Hoshangabad', 'Hoshiarpur',
  'Hospet', 'Howrah', 'Hubli-Dharwad', 'Hugli-Chinsurah', 'Hyderabad',
  'Ichalkaranji', 'Imphal', 'Indore', 'Itanagar', 'Itarsi', 'Jabalpur',
  'Jagadhri', 'Jagdalpur', 'Jaipur', 'Jalandhar', 'Jalgaon', 'Jalna',
  'Jalpaiguri', 'Jamalpur', 'Jammu', 'Jamnagar', 'Jamshedpur', 'Jaunpur',
  'Jehanabad', 'Jhansi', 'Jharsuguda', 'Jhunjhunu', 'Jind', 'Jodhpur',
  'Junagadh', 'Kadapa', 'Kaithal', 'Kakinada', 'Kalyan', 'Kamarhati',
  'Kanchipuram', 'Kanchrapara', 'Kanpur', 'Karaikudi', 'Karawal Nagar',
  'Karimnagar', 'Karnal', 'Kasaragod', 'Kashipur', 'Katihar', 'Khammam',
  'Khandwa', 'Kharagpur', 'Khora', 'Kirari Suleman Nagar', 'Kishanganj',
  'Kochi', 'Kohima', 'Kolhapur', 'Kolkata', 'Kollam', 'Korba', 'Kota',
  'Kottayam', 'Kozhikode', 'Krishnanagar', 'Kukatpally', 'Kumbakonam',
  'Kurnool', 'Lakhimpur', 'Lalitpur', 'Latur', 'Loni', 'Lucknow', 'Ludhiana',
  'Machilipatnam', 'Madanapalle', 'Madhyamgram', 'Madurai', 'Mahbubnagar',
  'Maheshtala', 'Malegaon', 'Maler Kotla', 'Mandi', 'Mandla', 'Mandsaur',
  'Mangalore', 'Mango', 'Mathura', 'Mau', 'Medininagar', 'Meerut', 'Mehsana',
  'Mira-Bhayandar', 'Miryalaguda', 'Mirzapur', 'Modinagar', 'Moga',
  'Moradabad', 'Morbi', 'Morena', 'Motihari', 'Mumbai', 'Munger', 'Murwara',
  'Mustafabad', 'Muzaffarnagar', 'Muzaffarpur', 'Mysore', 'Nabadwip',
  'Nadiad', 'Nagaon', 'Nagapattinam', 'Nagaur', 'Nagpur', 'Naihati',
  'Nalgonda', 'Namakkal', 'Nanded', 'Nandurbar', 'Nandyal', 'Narasaraopet',
  'Nashik', 'Navi Mumbai', 'Navsari', 'Nawada', 'Neemuch', 'Nellore',
  'New Delhi', 'Nizamabad', 'Noida', 'North Dumdum', 'Orai', 'Ozhukarai',
  'Pali', 'Pallavaram', 'Palwal', 'Panchkula', 'Panihati', 'Panipat', 'Panvel',
  'Parbhani', 'Patan', 'Pathankot', 'Patiala', 'Patna', 'Pilibhit', 'Pimpri-Chinchwad',
  'Pondicherry', 'Porbandar', 'Port Blair', 'Proddatur', 'Pudukkottai', 'Pune',
  'Purnia', 'Purulia', 'Raebareli', 'Raichur', 'Raiganj', 'Raigarh', 'Raipur',
  'Rajahmundry', 'Rajapalayam', 'Rajarhat Gopalpur', 'Rajkot', 'Rajnandgaon',
  'Rajpur Sonarpur', 'Ramagundam', 'Rampur', 'Ranchi', 'Ratlam', 'Raurkela',
  'Rewa', 'Rewari', 'Rohtak', 'Roorkee', 'Rourkela', 'Rudrapur', 'Sagar',
  'Saharanpur', 'Saharsa', 'Salem', 'Sambalpur', 'Sambhal', 'Sangli', 'Satara',
  'Satna', 'Sawai Madhopur', 'Secunderabad', 'Sehore', 'Serampore', 'Shahjahanpur',
  'Shamli', 'Shikohabad', 'Shillong', 'Shimla', 'Shivamogga', 'Shivpuri',
  'Sikar', 'Silchar', 'Siliguri', 'Singrauli', 'Sirsa', 'Sitapur', 'Solapur',
  'Sonipat', 'South Dumdum', 'Sri Ganganagar', 'Srinagar', 'Sultan Pur Majra',
  'Surat', 'Surendranagar', 'Suryapet', 'Tadepalligudem', 'Tadipatri',
  'Tenali', 'Thane', 'Thanesar', 'Thiruvananthapuram', 'Thoothukudi',
  'Thrissur', 'Tinsukia', 'Tiruchirappalli', 'Tirunelveli', 'Tirupati',
  'Tiruppur', 'Tiruvannamalai', 'Tiruvottiyur', 'Tumkur', 'Udaipur', 'Udupi',
  'Ujjain', 'Ulhasnagar', 'Uluberia', 'Unnao', 'Vadodara', 'Valsad',
  'Varanasi', 'Vasai-Virar', 'Vellore', 'Vidisha', 'Vijayawada', 'Viluppuram',
  'Visakhapatnam', 'Vizianagaram', 'Warangal', 'Wardha', 'Yamunanagar', 'Yavatmal'
];
